"""Seed models table with all supported model definitions.

Revision ID: 002_seed_models
Revises: 001_initial_schema
Create Date: 2026-06-03
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

import sqlalchemy as sa
from alembic import op

# ---------------------------------------------------------------------------
# Model seed data – derived from domain/model_definitions.py
# ---------------------------------------------------------------------------
MODELS_TO_SEED = [
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000001"),
        "model_id": "stabilityai/stable-diffusion-xl-base-1.0",
        "name": "SDXL 1.0",
        "source": "huggingface",
        "family": "stable_diffusion_xl",
        "variant": "1.0",
        "description": "SDXL is a major update to Stable Diffusion. It produces higher-resolution images and has improved text rendering.",
        "tags": ["diffusion", "image"],
        "source_url": "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0",
        "version": "1.0",
        "capabilities": ["text_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000002"),
        "model_id": "stabilityai/stable-diffusion-2-1",
        "name": "SD 2.1",
        "source": "huggingface",
        "family": "stable_diffusion_2",
        "variant": "2.1",
        "description": "Stable Diffusion v2.1 with improved aesthetics, better text rendering and safety classifier.",
        "tags": ["diffusion", "image"],
        "source_url": "https://huggingface.co/stabilityai/stable-diffusion-2-1",
        "version": "2.1",
        "capabilities": ["text_to_image", "image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000003"),
        "model_id": "runwayml/stable-diffusion-v1-5",
        "name": "SD 1.5",
        "source": "huggingface",
        "family": "stable_diffusion_1",
        "variant": "1.5",
        "description": "Stable Diffusion v1.5, the most versatile model with a huge community and ecosystem of LoRAs and ControlNets.",
        "tags": ["diffusion", "image"],
        "source_url": "https://huggingface.co/runwayml/stable-diffusion-v1-5",
        "version": "1.5",
        "capabilities": ["text_to_image", "image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000004"),
        "model_id": "timothybrooks/controlnet-canny-sd-xl-v10",
        "name": "ControlNet Canny XL",
        "source": "huggingface",
        "family": "controlnet",
        "variant": "canny-xl",
        "description": "ControlNet adapter for SDXL that guides generation with edge maps (canny edges).",
        "tags": ["controlnet", "canny", "adapter"],
        "source_url": "https://huggingface.co/timothybrooks/controlnet-canny-sd-xl-v10",
        "version": "1.0",
        "capabilities": ["image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000005"),
        "model_id": "lllyasviel/control_v11p_sd15_depth",
        "name": "ControlNet Depth SD1.5",
        "source": "huggingface",
        "family": "controlnet",
        "variant": "depth-sd15",
        "description": "ControlNet adapter for SD 1.5 that guides generation with depth maps.",
        "tags": ["controlnet", "depth", "adapter"],
        "source_url": "https://huggingface.co/lllyasviel/control_v11p_sd15_depth",
        "version": "1.1",
        "capabilities": ["image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000006"),
        "model_id": "lllyasviel/sd-controlnet-lineart",
        "name": "ControlNet Lineart SD1.5",
        "source": "huggingface",
        "family": "controlnet",
        "variant": "lineart-sd15",
        "description": "ControlNet adapter for SD 1.5 that guides generation with line art / sketches.",
        "tags": ["controlnet", "lineart", "adapter"],
        "source_url": "https://huggingface.co/lllyasviel/sd-controlnet-lineart",
        "version": "1.0",
        "capabilities": ["image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000007"),
        "model_id": "lambdalabs/sd-image-vary",
        "name": "Stable Image Vary",
        "source": "huggingface",
        "family": "stable_diffusion_xl",
        "variant": "image_vary",
        "description": "Fast image variation model based on SDXL. Creates variations of an input image.",
        "tags": ["diffusion", "image_variation"],
        "source_url": "https://huggingface.co/lambdalabs/sd-image-vary",
        "version": "1.0",
        "capabilities": ["image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000008"),
        "model_id": "lambdalabs/sd-image-compose",
        "name": "Stable Image Compose",
        "source": "huggingface",
        "family": "stable_diffusion_xl",
        "variant": "image_compose",
        "description": "Fast image composition model based on SDXL. Composes elements from an image with text guidance.",
        "tags": ["diffusion", "image_composition"],
        "source_url": "https://huggingface.co/lambdalabs/sd-image-compose",
        "version": "1.0",
        "capabilities": ["image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000009"),
        "model_id": "multimodalart/super-novelai-4.0-xl",
        "name": "Super NovelAI 4.0 XL",
        "source": "huggingface",
        "family": "custom",
        "variant": "novelai-xl",
        "description": "SDXL fine-tune trained on a large subset of the NovelAI dataset. Great for anime and illustrative styles.",
        "tags": ["diffusion", "anime", "illustration"],
        "source_url": "https://huggingface.co/multimodalart/super-novelai-4.0-xl",
        "version": "4.0",
        "capabilities": ["text_to_image", "image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000010"),
        "model_id": "alibaba-pai/Pai-2B",
        "name": "Pai-2B (Alibaba)",
        "source": "huggingface",
        "family": "llm",
        "variant": "pai-2b",
        "description": "Alibaba's Pai-2B LLM (7B params) for prompt enhancement and image-to-text description tasks.",
        "tags": ["llm", "prompt_enhancement"],
        "source_url": "https://huggingface.co/alibaba-pai/Pai-2B",
        "version": "2B",
        "capabilities": ["prompt_enhancement", "image_description"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000011"),
        "model_id": "meta-llama/Llama-3.2-3B-Instruct",
        "name": "Llama 3.2 3B Instruct",
        "source": "huggingface",
        "family": "llm",
        "variant": "llama-3.2-3b",
        "description": "Llama 3.2 3B Instruct is optimized for agentic prompting tasks. Can enhance prompts and describe images.",
        "tags": ["llm", "prompt_enhancement"],
        "source_url": "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct",
        "version": "3.2",
        "capabilities": ["prompt_enhancement", "image_description"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000012"),
        "model_id": "openai/whisper-large-v3",
        "name": "Whisper Large v3",
        "source": "huggingface",
        "family": "llm",
        "variant": "whisper-large",
        "description": "Whisper Large v3 is a state-of-the-art speech recognition model. Supports 99 languages and can transcribe and translate audio.",
        "tags": ["llm", "speech_to_text"],
        "source_url": "https://huggingface.co/openai/whisper-large-v3",
        "version": "large-v3",
        "capabilities": ["speech_to_text"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000013"),
        "model_id": "openai/whisper-large",
        "name": "Whisper Large",
        "source": "huggingface",
        "family": "llm",
        "variant": "whisper-large",
        "description": "Whisper Large supports 99 languages and can transcribe and translate audio.",
        "tags": ["llm", "speech_to_text"],
        "source_url": "https://huggingface.co/openai/whisper-large",
        "version": "large",
        "capabilities": ["speech_to_text"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000014"),
        "model_id": "facebook/detr-resnet-50",
        "name": "DETR ResNet-50 (Object Detection)",
        "source": "huggingface",
        "family": "vision",
        "variant": "detr-resnet50",
        "description": "DETR (DEtection TRansformer) with ResNet-50 backbone for object detection in images.",
        "tags": ["vision", "object_detection"],
        "source_url": "https://huggingface.co/facebook/detr-resnet-50",
        "version": "resnet-50",
        "capabilities": ["object_detection"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000015"),
        "model_id": "facebook/detr-resnet-50-panoptic",
        "name": "DETR ResNet-50 (Panoptic Segmentation)",
        "source": "huggingface",
        "family": "vision",
        "variant": "detr-resnet50-panoptic",
        "description": "DETR with ResNet-50 backbone for panoptic segmentation (combines semantic segmentation and instance detection).",
        "tags": ["vision", "panoptic_segmentation"],
        "source_url": "https://huggingface.co/facebook/detr-resnet-50-panoptic",
        "version": "resnet-50-panoptic",
        "capabilities": ["panoptic_segmentation"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000016"),
        "model_id": "facebook/detr-resnet-50-panoptic",
        "name": "DETR ResNet-50 (Semantic Segmentation)",
        "source": "huggingface",
        "family": "vision",
        "variant": "detr-resnet50-semantic",
        "description": "DETR with ResNet-50 backbone for semantic segmentation of images.",
        "tags": ["vision", "semantic_segmentation"],
        "source_url": "https://huggingface.co/facebook/detr-resnet-50-panoptic",
        "version": "resnet-50-semantic",
        "capabilities": ["semantic_segmentation"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000017"),
        "model_id": "stabilityai/stable-video-diffusion-img2vid-xt",
        "name": "SVD-XT 1.0",
        "source": "huggingface",
        "family": "svd_xt",
        "variant": "1.0",
        "description": "A video model for turning an input image into a video. The model takes an image-plus-noise as the starting point and generates an animation that shows a slow evolution of the input image.",
        "tags": ["diffusion", "video", "image_to_video"],
        "source_url": "https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt",
        "version": "1.0",
        "capabilities": ["text_to_image", "image_to_image", "image_to_video"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
    },
]


def upgrade() -> None:
    """Insert seed model records using INSERT ... ON CONFLICT DO NOTHING."""
    conn = op.get_bind()
    meta = sa.MetaData()
    models_table = sa.Table(
        "models",
        meta,
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True)),
        sa.Column("model_id", sa.String(512)),
        sa.Column("name", sa.String(255)),
        sa.Column("source", sa.String(50)),
        sa.Column("family", sa.String(50)),
        sa.Column("variant", sa.String(100)),
        sa.Column("description", sa.Text),
        sa.Column("tags", sa.dialects.postgresql.JSONB),
        sa.Column("source_url", sa.String(1024)),
        sa.Column("version", sa.String(100)),
        sa.Column("capabilities", sa.dialects.postgresql.JSONB),
        sa.Column("total_size_bytes", sa.BigInteger),
        sa.Column("disk_size_bytes", sa.BigInteger),
        sa.Column("file_path", sa.String(1024)),
        sa.Column("status", sa.String(50)),
        sa.Column("download_progress", sa.Integer),
        sa.Column("checksum", sa.String(128)),
        sa.Column("is_verified", sa.Boolean),
        sa.Column("last_verified_at", sa.DateTime(timezone=True)),
        sa.Column("created_at", sa.DateTime(timezone=True)),
        sa.Column("updated_at", sa.DateTime(timezone=True)),
    )

    now = datetime.now(timezone.utc)

    for m in MODELS_TO_SEED:
        row = {
            "id": m["id"],
            "model_id": m["model_id"],
            "name": m["name"],
            "source": m["source"],
            "family": m["family"],
            "variant": m["variant"],
            "description": m["description"],
            "tags": m["tags"],
            "source_url": m["source_url"],
            "version": m["version"],
            "capabilities": m["capabilities"],
            "total_size_bytes": m["total_size_bytes"],
            "disk_size_bytes": m["disk_size_bytes"],
            "file_path": m["file_path"],
            "status": m["status"],
            "download_progress": m["download_progress"],
            "checksum": m["checksum"],
            "is_verified": m["is_verified"],
            "last_verified_at": None,
            "created_at": now,
            "updated_at": now,
        }
        insert_stmt = models_table.insert().values(row)
        # Use PostgreSQL ON CONFLICT DO NOTHING so re-runs are safe
        insert_stmt = insert_stmt.prefix_with("IGNORE")
        conn.execute(insert_stmt)


def downgrade() -> None:
    """Remove all seed model records."""
    conn = op.get_bind()
    meta = sa.MetaData()
    models_table = sa.Table(
        "models",
        meta,
        sa.Column("model_id", sa.String(512)),
    )
    model_ids = [m["model_id"] for m in MODELS_TO_SEED]
    conn.execute(models_table.delete().where(models_table.c.model_id.in_(model_ids)))