"""Seed models table with all supported model definitions.

Revision ID: 002_seed_models
Revises: 001_initial_schema
Create Date: 2026-06-03
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

import sqlalchemy as sa
from alembic import op

# revision identifiers
revision = "002_seed_models"
down_revision = "001_initial_schema"
branch_labels = None
depends_on = None

# ---------------------------------------------------------------------------
# Model seed data
# ---------------------------------------------------------------------------
MODELS_TO_SEED = [
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000001"),
        "model_id": "stabilityai/stable-diffusion-xl-base-1.0",
        "name": "SDXL 1.0",
        "source": "huggingface",
        "family": "stable_diffusion_xl",
        "variant": "1.0",
        "description": "Stable Diffusion XL 1.0 is Stability AI's flagship SDXL base model, built for higher image quality, stronger prompt adherence, and better composition than earlier Stable Diffusion releases. It excels at 1024px generation, handles lighting and scene structure well, and is especially strong for detailed illustrations, concept art, product-style imagery, and polished general-purpose text-to-image work. It is also a strong foundation model for fine-tunes, refiner pipelines, and advanced workflows that need better realism and cleaner text rendering.",
        "tags": ["diffusion", "image"],
        "source_url": "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0",
        "version": "1.0",
        "capabilities": ["text_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 6930000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 8,
        "recommended_vram_max_gb": 16,
        "license": "openrail++",
        "base_model": "sdxl",
        "precision": "fp16",
        "requirements": {"recommended_resolution": "1024x1024"},
        "notes": "Base SDXL model; commonly used with a separate refiner in advanced workflows.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000002"),
        "model_id": "stabilityai/stable-diffusion-2-1",
        "name": "SD 2.1",
        "source": "huggingface",
        "family": "stable_diffusion_2",
        "variant": "2.1",
        "description": "Stable Diffusion 2.1 is a refined general-purpose diffusion model that improves on the 2.x line with better image coherence, cleaner aesthetics, and more reliable prompt interpretation. It performs well for stylized artwork, environments, portraits, and design exploration, while often producing more consistent structure than older SD 1.x checkpoints. Its strengths are balanced image quality, solid text-guided generation, and compatibility with many image-to-image workflows for iterative creative work.",
        "tags": ["diffusion", "image"],
        "source_url": "https://huggingface.co/stabilityai/stable-diffusion-2-1",
        "version": "2.1",
        "capabilities": ["text_to_image", "image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 5510000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "openrail++",
        "base_model": "sd2.1",
        "precision": "fp16",
        "requirements": {"recommended_resolution": "768x768"},
        "notes": "General-purpose SD 2.x checkpoint with stronger structure than many SD 1.x models.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000003"),
        "model_id": "runwayml/stable-diffusion-v1-5",
        "name": "SD 1.5",
        "source": "huggingface",
        "family": "stable_diffusion_1",
        "variant": "1.5",
        "description": "Stable Diffusion 1.5 is one of the most widely adopted open image models and remains a favorite because of its flexibility, speed, and enormous ecosystem. Its biggest strength is compatibility: countless LoRAs, embeddings, ControlNets, fine-tunes, and community workflows are built around it. It is especially effective for rapid experimentation, stylized art, anime, character work, and custom pipelines where broad tool support matters more than raw base-model realism.",
        "tags": ["diffusion", "image"],
        "source_url": "https://huggingface.co/runwayml/stable-diffusion-v1-5",
        "version": "1.5",
        "capabilities": ["text_to_image", "image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 4260000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 4,
        "recommended_vram_max_gb": 10,
        "license": "creativeml-openrail-m",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"recommended_resolution": "512x512"},
        "notes": "Very broad ecosystem support; ideal for LoRAs, embeddings, and older community workflows.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000004"),
        "model_id": "timothybrooks/controlnet-canny-sd-xl-v10",
        "name": "ControlNet Canny XL",
        "source": "huggingface",
        "family": "controlnet",
        "variant": "canny-xl",
        "description": "ControlNet Canny XL is a ControlNet adapter for SDXL that uses Canny edge maps to preserve the structure of an input image while still allowing the prompt to guide style and detail. Its main strength is composition control: silhouettes, object placement, outlines, and major shapes stay much closer to the source than in unguided generation. It is especially useful for redesigning photos, keeping layout consistency, stylizing sketches, and producing prompt-driven variations without losing the original scene geometry.",
        "tags": ["controlnet", "canny", "adapter"],
        "source_url": "https://huggingface.co/timothybrooks/controlnet-canny-sd-xl-v10",
        "version": "1.0",
        "capabilities": ["image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 3600000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 10,
        "recommended_vram_max_gb": 16,
        "license": "openrail++",
        "base_model": "sdxl",
        "precision": "fp16",
        "requirements": {"requires_base_model": "stabilityai/stable-diffusion-xl-base-1.0"},
        "notes": "Requires an SDXL-compatible base model; used as a structural conditioning adapter, not standalone generation.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000005"),
        "model_id": "lllyasviel/control_v11p_sd15_depth",
        "name": "ControlNet Depth SD1.5",
        "source": "huggingface",
        "family": "controlnet",
        "variant": "depth-sd15",
        "description": "ControlNet Depth for SD 1.5 guides generation with a depth map, helping the model understand spatial relationships, foreground-background separation, and scene layout. Its strong point is preserving 3D structure while letting the prompt alter style, materials, mood, or subject details. It works particularly well for architecture, interiors, landscapes, and photo-to-art transformations where maintaining believable perspective and depth is more important than copying exact edges.",
        "tags": ["controlnet", "depth", "adapter"],
        "source_url": "https://huggingface.co/lllyasviel/control_v11p_sd15_depth",
        "version": "1.1",
        "capabilities": ["image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 1450000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "openrail",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"requires_base_model": "runwayml/stable-diffusion-v1-5"},
        "notes": "Depth-guided ControlNet adapter for SD 1.5 workflows.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000006"),
        "model_id": "lllyasviel/sd-controlnet-lineart",
        "name": "ControlNet Lineart SD1.5",
        "source": "huggingface",
        "family": "controlnet",
        "variant": "lineart-sd15",
        "description": "ControlNet Lineart for SD 1.5 is designed to turn line drawings, clean sketches, and extracted contour art into fully rendered images while preserving the original drawing structure. Its main strengths are pose retention, shape consistency, and strong support for illustration workflows. It is ideal for concept art, comic-style pipelines, anime workflows, and sketch-to-image generation where the artist wants the final output to closely follow the source drawing instead of drifting compositionally.",
        "tags": ["controlnet", "lineart", "adapter"],
        "source_url": "https://huggingface.co/lllyasviel/sd-controlnet-lineart",
        "version": "1.0",
        "capabilities": ["image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 1450000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "openrail",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"requires_base_model": "runwayml/stable-diffusion-v1-5"},
        "notes": "Lineart/sketch-guided ControlNet adapter for SD 1.5 illustration workflows.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000007"),
        "model_id": "lambdalabs/sd-image-vary",
        "name": "Stable Image Vary",
        "source": "huggingface",
        "family": "stable_diffusion_xl",
        "variant": "image_vary",
        "description": "Stable Image Vary is an image-variation model focused on generating alternate versions of an input image while keeping its overall identity, composition, and visual intent. Its strongest use case is controlled exploration: you can create new takes on a concept, product shot, illustration, or composition without starting over from pure text. It is well suited for ideation, visual A/B testing, style changes, and iterative refinement when you want novelty with continuity.",
        "tags": ["diffusion", "image_variation"],
        "source_url": "https://huggingface.co/lambdalabs/sd-image-vary",
        "version": "1.0",
        "capabilities": ["image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 4200000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 8,
        "recommended_vram_max_gb": 16,
        "license": "",
        "base_model": "sdxl",
        "precision": "fp16",
        "requirements": {"input_type": "image"},
        "notes": "Variation-focused image-to-image model for preserving identity and composition while exploring alternatives.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000008"),
        "model_id": "lambdalabs/sd-image-compose",
        "name": "Stable Image Compose",
        "source": "huggingface",
        "family": "stable_diffusion_xl",
        "variant": "image_compose",
        "description": "Stable Image Compose is built for prompt-guided image composition, helping combine visual elements from an existing image with new textual instructions. Its strength is selective transformation: it can preserve useful source content while reinterpreting arrangement, mood, styling, or added concepts. This makes it valuable for creative direction, advertising mockups, remix workflows, and design iteration where text alone is too vague but the source image should not be copied rigidly.",
        "tags": ["diffusion", "image_composition"],
        "source_url": "https://huggingface.co/lambdalabs/sd-image-compose",
        "version": "1.0",
        "capabilities": ["image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 4200000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 8,
        "recommended_vram_max_gb": 16,
        "license": "",
        "base_model": "sdxl",
        "precision": "fp16",
        "requirements": {"input_type": "image"},
        "notes": "Composition-oriented image-to-image model for mixing source visual structure with prompt changes.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000009"),
        "model_id": "multimodalart/super-novelai-4.0-xl",
        "name": "Super NovelAI 4.0 XL",
        "source": "huggingface",
        "family": "custom",
        "variant": "novelai-xl",
        "description": "Super NovelAI 4.0 XL is an SDXL-based fine-tune aimed at anime, stylized character art, and highly illustrative imagery. It stands out for vibrant color use, expressive character rendering, polished line quality, and strong performance on fantasy, cosplay, and visually dramatic scenes. Compared with more neutral base models, its strength is aesthetic bias: it more readily produces appealing illustrative outputs with less prompt effort, especially for users targeting anime-inspired or painterly visual styles.",
        "tags": ["diffusion", "anime", "illustration"],
        "source_url": "https://huggingface.co/multimodalart/super-novelai-4.0-xl",
        "version": "4.0",
        "capabilities": ["text_to_image", "image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 6900000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 8,
        "recommended_vram_max_gb": 16,
        "license": "",
        "base_model": "sdxl",
        "precision": "fp16",
        "requirements": {"recommended_resolution": "1024x1024"},
        "notes": "SDXL fine-tune biased toward anime and stylized illustration output.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000010"),
        "model_id": "alibaba-pai/Pai-2B",
        "name": "Pai-2B (Alibaba)",
        "source": "huggingface",
        "family": "llm",
        "variant": "pai-2b",
        "description": "Pai-2B is a compact language model from Alibaba suited to lightweight text-generation tasks where low resource usage matters. In a creative imaging stack, its strengths are prompt rewriting, prompt expansion, caption-style description, and fast general language assistance without the overhead of a much larger model. It is useful for turning rough user ideas into richer prompts, extracting concise scene descriptions, and supporting automation pipelines that need inexpensive text reasoning rather than deep long-context analysis.",
        "tags": ["llm", "prompt_enhancement"],
        "source_url": "https://huggingface.co/alibaba-pai/Pai-2B",
        "version": "2B",
        "capabilities": ["prompt_enhancement", "image_description"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 4000000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 4,
        "recommended_vram_max_gb": 8,
        "license": "",
        "base_model": "",
        "precision": "fp16",
        "requirements": {"parameter_count": "2B"},
        "notes": "Compact LLM suitable for lightweight prompt rewriting and metadata generation.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000011"),
        "model_id": "meta-llama/Llama-3.2-3B-Instruct",
        "name": "Llama 3.2 3B Instruct",
        "source": "huggingface",
        "family": "llm",
        "variant": "llama-3.2-3b",
        "description": "Llama 3.2 3B Instruct is a small but capable instruction-tuned language model designed for efficient assistant-style tasks. Its strong points are clear prompt following, reliable rewriting, summarization, and structured output generation at relatively low compute cost. In multimodal or image-generation workflows, it is a strong choice for prompt enhancement, safety-aware rephrasing, tag generation, metadata creation, and turning user intent into cleaner, more descriptive prompts for downstream visual models.",
        "tags": ["llm", "prompt_enhancement"],
        "source_url": "https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct",
        "version": "3.2",
        "capabilities": ["prompt_enhancement", "image_description"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 6500000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 10,
        "license": "llama",
        "base_model": "llama-3.2",
        "precision": "fp16",
        "requirements": {"parameter_count": "3B"},
        "notes": "Instruction-tuned small LLM for efficient assistant and prompt enhancement tasks.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000012"),
        "model_id": "openai/whisper-large-v3",
        "name": "Whisper Large v3",
        "source": "huggingface",
        "family": "llm",
        "variant": "whisper-large",
        "description": "Whisper Large v3 is a top-tier open speech recognition model optimized for accurate multilingual transcription and translation. Its strengths include strong robustness to accents, background noise, varied speaking styles, and mixed-language audio, making it a dependable choice for real-world recordings rather than only clean studio speech. It is well suited for transcription pipelines, subtitles, voice interfaces, meeting notes, and media processing workflows that need high recognition quality across many languages.",
        "tags": ["llm", "speech_to_text"],
        "source_url": "https://huggingface.co/openai/whisper-large-v3",
        "version": "large-v3",
        "capabilities": ["speech_to_text"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 3100000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 8,
        "recommended_vram_max_gb": 12,
        "license": "apache-2.0",
        "base_model": "whisper",
        "precision": "fp16",
        "requirements": {"supports_translation": True},
        "notes": "Large multilingual ASR model; strong accuracy for transcription and translation workflows.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000013"),
        "model_id": "openai/whisper-large",
        "name": "Whisper Large",
        "source": "huggingface",
        "family": "llm",
        "variant": "whisper-large",
        "description": "Whisper Large is a high-capacity speech-to-text model known for strong multilingual transcription and speech translation performance. It handles conversational audio, diverse accents, and many recording conditions better than lightweight ASR models, making it useful for production transcription tasks. Its key strength is broad language coverage combined with solid zero-shot robustness, so it works well for interviews, podcasts, user-uploaded recordings, subtitles, and general audio understanding pipelines.",
        "tags": ["llm", "speech_to_text"],
        "source_url": "https://huggingface.co/openai/whisper-large",
        "version": "large",
        "capabilities": ["speech_to_text"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 3100000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 8,
        "recommended_vram_max_gb": 12,
        "license": "apache-2.0",
        "base_model": "whisper",
        "precision": "fp16",
        "requirements": {"supports_translation": True},
        "notes": "Large multilingual ASR model with broad language coverage and strong robustness.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000014"),
        "model_id": "facebook/detr-resnet-50",
        "name": "DETR ResNet-50 (Object Detection)",
        "source": "huggingface",
        "family": "vision",
        "variant": "detr-resnet50",
        "description": "DETR ResNet-50 is an object detection model that combines a ResNet-50 backbone with a transformer-based detection head. Its main advantage is a simpler, end-to-end detection approach that predicts objects directly without many of the hand-designed components used in older detectors. It is strong for general object localization and classification in natural images, making it a good fit for image analysis, scene understanding, content moderation, asset tagging, and computer vision pipelines that need reliable baseline detection.",
        "tags": ["vision", "object_detection"],
        "source_url": "https://huggingface.co/facebook/detr-resnet-50",
        "version": "resnet-50",
        "capabilities": ["object_detection"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 166000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 2,
        "recommended_vram_max_gb": 6,
        "license": "apache-2.0",
        "base_model": "detr",
        "precision": "fp32",
        "requirements": {"backbone": "resnet-50"},
        "notes": "General-purpose object detection model for natural images.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000015"),
        "model_id": "facebook/detr-resnet-50-panoptic",
        "name": "DETR ResNet-50 (Panoptic Segmentation)",
        "source": "huggingface",
        "family": "vision",
        "variant": "detr-resnet50-panoptic",
        "description": "DETR ResNet-50 Panoptic extends DETR into panoptic segmentation, combining object-level instance understanding with semantic labeling of background regions. Its key strength is unified scene parsing: it can identify countable objects and broader stuff categories in the same output. This makes it especially useful for robotics, scene decomposition, image editing tools, spatial reasoning, and advanced analysis workflows where knowing both what is present and where each region belongs is important.",
        "tags": ["vision", "panoptic_segmentation"],
        "source_url": "https://huggingface.co/facebook/detr-resnet-50-panoptic",
        "version": "resnet-50-panoptic",
        "capabilities": ["panoptic_segmentation"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 200000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 3,
        "recommended_vram_max_gb": 8,
        "license": "apache-2.0",
        "base_model": "detr",
        "precision": "fp32",
        "requirements": {"backbone": "resnet-50"},
        "notes": "Panoptic segmentation variant for unified object and background scene labeling.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000016"),
        "model_id": "facebook/detr-resnet-50-panoptic",
        "name": "DETR ResNet-50 (Semantic Segmentation)",
        "source": "huggingface",
        "family": "vision",
        "variant": "detr-resnet50-semantic",
        "description": "This DETR-based semantic segmentation configuration is suited to labeling image regions by class across the full scene rather than detecting only separate objects. Its strength is broad scene understanding: it helps determine which pixels belong to categories such as road, sky, building, person, or vegetation. That makes it useful for automated masking, image preprocessing, environment understanding, editing workflows, and analytics pipelines where dense per-pixel classification matters more than object bounding boxes.",
        "tags": ["vision", "semantic_segmentation"],
        "source_url": "https://huggingface.co/facebook/detr-resnet-50-panoptic",
        "version": "resnet-50-semantic",
        "capabilities": ["semantic_segmentation"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 200000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 3,
        "recommended_vram_max_gb": 8,
        "license": "apache-2.0",
        "base_model": "detr",
        "precision": "fp32",
        "requirements": {"backbone": "resnet-50"},
        "notes": "Semantic segmentation-oriented DETR configuration for dense scene labeling.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000017"),
        "model_id": "stabilityai/stable-video-diffusion-img2vid-xt",
        "name": "SVD-XT 1.0",
        "source": "huggingface",
        "family": "svd_xt",
        "variant": "1.0",
        "description": "Stable Video Diffusion XT 1.0 is an image-to-video diffusion model designed to animate a single input image into a short, coherent video clip. Its strongest qualities are motion synthesis, temporal consistency, and the ability to preserve the identity and composition of the starting frame while introducing cinematic movement. It is especially effective for turning illustrations, concept frames, portraits, or product visuals into dynamic clips for previews, social content, prototypes, and creative motion studies.",
        "tags": ["diffusion", "video", "image_to_video"],
        "source_url": "https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt",
        "version": "1.0",
        "capabilities": ["text_to_image", "image_to_image", "image_to_video"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 9800000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 12,
        "recommended_vram_max_gb": 24,
        "license": "ai-community",
        "base_model": "svd-xt",
        "precision": "fp16",
        "requirements": {"input_type": "image", "output_type": "video"},
        "notes": "Image-to-video model with heavier VRAM requirements than standard still-image diffusion models.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000018"),
        "model_id": "huggingshu/realvisxl-v5",
        "name": "RealVisXL V5",
        "source": "huggingface",
        "family": "custom",
        "variant": "realvisxl-v5",
        "description": "RealVisXL V5 is an SDXL fine-tune focused on realistic, polished, high-detail image generation. It is especially strong for portraits, fashion, product-style renders, cinematic scenes, and photorealistic compositions with appealing lighting and refined textures. Compared with a neutral base checkpoint, its advantage is that it more readily produces camera-like results with less prompt tuning, making it a popular choice for users who want realism, attractive skin tones, strong depth, and visually finished outputs out of the box.",
        "tags": ["custom", "diffusion", "image"],
        "source_url": "https://huggingface.co/huggingshu/realvisxl-v5",
        "version": "5.0",
        "capabilities": ["text_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 6900000000,
        "file_path": "",
        "status": "not_downloaded",
        "download_progress": 0,
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 8,
        "recommended_vram_max_gb": 16,
        "license": "",
        "base_model": "sdxl",
        "precision": "fp16",
        "requirements": {"recommended_resolution": "1024x1024"},
        "notes": "Photorealistic SDXL fine-tune optimized for polished realistic outputs.",
    },
]

def upgrade() -> None:
    """Insert seed model records using INSERT ... ON CONFLICT DO NOTHING."""
    conn = op.get_bind()
    meta = sa.MetaData()
    models_table = sa.Table(
        "models",
        meta,
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True)),
        sa.Column("model_id", sa.String(512)),
        sa.Column("name", sa.String(255)),
        sa.Column("preferred_name", sa.String(255)),
        sa.Column("source", sa.String(50)),
        sa.Column("family", sa.String(50)),
        sa.Column("variant", sa.String(100)),
        sa.Column("description", sa.Text),
        sa.Column("tags", sa.dialects.postgresql.JSONB),
        sa.Column("source_url", sa.String(1024)),
        sa.Column("version", sa.String(100)),
        sa.Column("capabilities", sa.dialects.postgresql.JSONB),
        sa.Column("total_size_bytes", sa.BigInteger),
        sa.Column("disk_size_bytes", sa.BigInteger),
        sa.Column("download_size_bytes", sa.BigInteger),
        sa.Column("file_path", sa.String(1024)),
        sa.Column("status", sa.String(50)),
        sa.Column("download_progress", sa.Float),
        sa.Column("checksum", sa.String(512)),
        sa.Column("is_verified", sa.Boolean),
        sa.Column("recommended_vram_min_gb", sa.Integer),
        sa.Column("recommended_vram_max_gb", sa.Integer),
        sa.Column("license", sa.String(200)),
        sa.Column("base_model", sa.String(100)),
        sa.Column("precision", sa.String(20)),
        sa.Column("requirements", sa.dialects.postgresql.JSONB),
        sa.Column("notes", sa.Text),
        sa.Column("created_at", sa.DateTime),
        sa.Column("updated_at", sa.DateTime),
    )
    
    # Get current timestamp
    now = datetime.now(timezone.utc)
    
    # Prepare model records
    model_records = []
    for model_data in MODELS_TO_SEED:
        record = model_data.copy()
        record["created_at"] = now
        record["updated_at"] = now
        model_records.append(record)
    
    # Insert all models with ON CONFLICT DO NOTHING
    if model_records:
        insert_stmt = sa.sql.insert(models_table).on_conflict_do_nothing(
            index_elements=["model_id"]
        )
        for record in model_records:
            conn.execute(insert_stmt.values(**record))

def downgrade() -> None:
    """Remove all seed model records."""
    conn = op.get_bind()
    meta = sa.MetaData()
    models_table = sa.Table(
        "models",
        meta,
        sa.Column("model_id", sa.String(512)),
    )
    model_ids = [m["model_id"] for m in MODELS_TO_SEED]
    conn.execute(models_table.delete().where(models_table.c.model_id.in_(model_ids)))