"""Seed models table with all supported model definitions.

Revision ID: 002_seed_models
Revises: 001_initial_schema
Create Date: 2026-06-03
"""

from __future__ import annotations

import json
import uuid
from datetime import datetime, timezone

import sqlalchemy as sa
from sqlalchemy import text
from alembic import op

# revision identifiers
revision = "002_seed_models"
down_revision = "001_initial_schema"
branch_labels = None
depends_on = None

# ---------------------------------------------------------------------------
# Model seed data
# ---------------------------------------------------------------------------
MODELS_TO_SEED = [
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000001"),
        "model_id": "stabilityai/stable-diffusion-xl-base-1.0",
        "name": "SDXL 1.0",
        "preferred_name": "SDXL 1.0",
        "source": "huggingface",
        "family": "stable_diffusion_xl",
        "variant": "1.0",
        "description": "Best for: general text-to-image and generic image-to-image work. Strengths: balanced quality, good prompt following, and strong composition at 1024 resolution. Use it when you want one neutral all-around model. Not a helper model.",
        "tags": ["diffusion", "image", "text_to_image", "image_to_image", "all-arounder", "general-purpose", "neutral-style"],
        "source_url": "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0",
        "version": "1.0",
        "capabilities": ["text_to_image", "image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 6930000000,
        "file_path": "",
        "status": "not_downloaded",
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 8,
        "recommended_vram_max_gb": 16,
        "license": "openrail++",
        "base_model": "sdxl",
        "precision": "fp16",
        "requirements": {"recommended_resolution": "1024x1024"},
        "notes": "Base SDXL model; best default all-arounder.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000002"),
        "model_id": "stabilityai/stable-diffusion-2-1",
        "name": "SD 2.1",
        "preferred_name": "SD 2.1",
        "source": "huggingface",
        "family": "stable_diffusion_2",
        "variant": "2.1",
        "description": "Best for: generic image-to-image and lighter general generation. Strengths: decent structure, lower resource needs than SDXL, and flexible use in broad workflows. Use it when you want a practical non-SDXL default. Not a helper model.",
        "tags": ["diffusion", "image", "text_to_image", "image_to_image", "general-purpose", "generic-transform", "balanced"],
        "source_url": "https://huggingface.co/stabilityai/stable-diffusion-2-1",
        "version": "2.1",
        "capabilities": ["text_to_image", "image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 5510000000,
        "file_path": "",
        "status": "not_downloaded",
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "openrail++",
        "base_model": "sd2.1",
        "precision": "fp16",
        "requirements": {"recommended_resolution": "768x768"},
        "notes": "Useful generic model for transformations and experiments.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000003"),
        "model_id": "runwayml/stable-diffusion-v1-5",
        "name": "SD 1.5 Test Model",
        "preferred_name": "SD 1.5 Test Model",
        "source": "huggingface",
        "family": "stable_diffusion_1",
        "variant": "1.5",
        "description": "Best for: testing your platform, not final quality. Strengths: lighter weight, broad compatibility, and fast checks for routes, queues, prompts, and UI behavior. Use it when you want a cheap test model to verify the app works end-to-end. Not a helper model.",
        "tags": ["diffusion", "image", "text_to_image", "image_to_image", "test-model", "lightweight", "dev-testing"],
        "source_url": "https://huggingface.co/runwayml/stable-diffusion-v1-5",
        "version": "1.5",
        "capabilities": ["text_to_image", "image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 4260000000,
        "file_path": "",
        "status": "not_downloaded",
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 4,
        "recommended_vram_max_gb": 10,
        "license": "creativeml-openrail-m",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"recommended_resolution": "512x512"},
        "notes": "Designated test model only.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000004"),
        "model_id": "huggingshu/realvisxl-v5",
        "name": "RealVisXL V5",
        "preferred_name": "RealVisXL V5",
        "source": "huggingface",
        "family": "custom",
        "variant": "realvisxl-v5",
        "description": "Best for: realistic portraits, fashion shots, product images, and polished photorealistic scenes. Strengths: camera-like lighting, cleaner skin and texture, and strong realism without much prompt tuning. Use it when you want realistic output fast. Not a helper model.",
        "tags": ["custom", "diffusion", "image", "text_to_image", "realistic", "photorealistic", "portrait", "product-style"],
        "source_url": "https://huggingface.co/huggingshu/realvisxl-v5",
        "version": "5.0",
        "capabilities": ["text_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 6900000000,
        "file_path": "",
        "status": "not_downloaded",
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 8,
        "recommended_vram_max_gb": 16,
        "license": "",
        "base_model": "sdxl",
        "precision": "fp16",
        "requirements": {"recommended_resolution": "1024x1024"},
        "notes": "Main realistic specialist for text-to-image.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000005"),
        "model_id": "multimodalart/super-novelai-4.0-xl",
        "name": "Super NovelAI 4.0 XL",
        "preferred_name": "Super NovelAI 4.0 XL",
        "source": "huggingface",
        "family": "custom",
        "variant": "novelai-xl",
        "description": "Best for: anime characters, fantasy scenes, and colorful stylized illustrations. Strengths: strong illustrative bias, expressive character rendering, and vibrant color without much prompt tuning. Use it when you want anime or stylized art instead of realism. Not a helper model.",
        "tags": ["diffusion", "anime", "illustration", "text_to_image", "image_to_image", "anime-style", "stylized", "character-art"],
        "source_url": "https://huggingface.co/multimodalart/super-novelai-4.0-xl",
        "version": "4.0",
        "capabilities": ["text_to_image", "image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 6900000000,
        "file_path": "",
        "status": "not_downloaded",
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 8,
        "recommended_vram_max_gb": 16,
        "license": "",
        "base_model": "sdxl",
        "precision": "fp16",
        "requirements": {"recommended_resolution": "1024x1024"},
        "notes": "Main anime and stylized specialist.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000006"),
        "model_id": "lambdalabs/sd-image-variations-diffusers",
        "name": "Stable Image Variations",
        "preferred_name": "Stable Image Variations",
        "source": "huggingface",
        "family": "stable_diffusion_1",
        "variant": "image_variations",
        "description": "Best for: making alternate versions of an existing image. Strengths: keeps the overall idea and identity better than generic image-to-image while still producing new outputs. Use it when the user wants variations, not a total redesign. Not a helper model.",
        "tags": ["diffusion", "image", "image_to_image", "variation", "identity-preserving", "concept-variation"],
        "source_url": "https://huggingface.co/lambdalabs/sd-image-variations-diffusers",
        "version": "2.0",
        "capabilities": ["image_to_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 4200000000,
        "file_path": "",
        "status": "not_downloaded",
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "creativeml-openrail-m",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"input_type": "image"},
        "notes": "Best for variation-style image-to-image behavior.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000007"),
        "model_id": "timbrooks/instruct-pix2pix",
        "name": "InstructPix2Pix",
        "preferred_name": "InstructPix2Pix",
        "source": "huggingface",
        "family": "stable_diffusion_edit",
        "variant": "pix2pix",
        "description": "Best for: prompt-based image edits like recoloring, style changes, mood changes, and object tweaks. Strengths: follows edit instructions directly and works well when the user says things like 'make it blue' or 'change the style'. Use it when you want editing by instruction, not pure variation. Not a helper model.",
        "tags": ["diffusion", "image", "image_to_image", "recolor_image", "instruction-editing", "edit-by-text", "style-transfer", "global-edit"],
        "source_url": "https://huggingface.co/timbrooks/instruct-pix2pix",
        "version": "1.0",
        "capabilities": ["image_to_image", "recolor_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 4900000000,
        "file_path": "",
        "status": "not_downloaded",
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "openrail",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"input_type": "image"},
        "notes": "Primary recolor and instruction-based editing model.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000008"),
        "model_id": "stabilityai/stable-diffusion-x4-upscaler",
        "name": "Stable Diffusion x4 Upscaler",
        "preferred_name": "SD x4 Upscaler",
        "source": "huggingface",
        "family": "stable_diffusion_upscaler",
        "variant": "x4",
        "description": "Best for: making images bigger and cleaner. Strengths: dedicated upscaling behavior, better fit for enlargement than generic image-to-image, and useful texture recovery. Use it when the main goal is higher resolution with less creative drift. Not a helper model.",
        "tags": ["diffusion", "image", "upscale_image", "detail-restoration", "resolution-enhancement", "sharpening", "enhancement"],
        "source_url": "https://huggingface.co/stabilityai/stable-diffusion-x4-upscaler",
        "version": "x4",
        "capabilities": ["image_to_image", "upscale_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 5100000000,
        "file_path": "",
        "status": "not_downloaded",
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 8,
        "recommended_vram_max_gb": 16,
        "license": "openrail++",
        "base_model": "sd2-upscaler",
        "precision": "fp16",
        "requirements": {"input_type": "image", "scale_factor": "4x"},
        "notes": "Primary dedicated upscaler.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000009"),
        "model_id": "Salesforce/blip-image-captioning-large",
        "name": "BLIP Image Captioning Large",
        "preferred_name": "BLIP Caption Large",
        "source": "huggingface",
        "family": "vision_language",
        "variant": "caption-large",
        "description": "Best for: describing what is in an image in plain language. Strengths: solid caption quality and easy use for alt text, summaries, and scene descriptions. Use it when your route needs to explain an image, not generate one. Not a helper model.",
        "tags": ["vision-language", "describe_image", "captioning", "image-description", "scene-summary"],
        "source_url": "https://huggingface.co/Salesforce/blip-image-captioning-large",
        "version": "large",
        "capabilities": ["image_description"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 990000000,
        "file_path": "",
        "status": "not_downloaded",
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 4,
        "recommended_vram_max_gb": 8,
        "license": "bsd-3-clause",
        "base_model": "blip",
        "precision": "fp16",
        "requirements": {"input_type": "image"},
        "notes": "Primary describe_image model.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000010"),
        "model_id": "lllyasviel/control_v11f1p_sd15_depth",
        "name": "ControlNet Depth SD1.5",
        "preferred_name": "ControlNet Depth SD1.5",
        "source": "huggingface",
        "family": "controlnet",
        "variant": "depth-sd15",
        "description": "Best for: structure-aware edits where depth and spatial layout matter. This is a helper model. Strengths: preserves foreground-background relationships and scene geometry better than generic image-to-image. Best helper target: pair it with SD 1.5 Test Model for lightweight controlled workflows, or with another SD1.5-compatible base if you add one later. Use it for interiors, landscapes, architecture, and recolor/edit tasks where depth must stay believable.",
        "tags": ["controlnet", "adapter", "helper", "image_to_image", "recolor_image", "depth-guided", "spatial-control", "structure-preserving"],
        "source_url": "https://huggingface.co/lllyasviel/control_v11f1p_sd15_depth",
        "version": "1.1",
        "capabilities": ["image_to_image", "recolor_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 1450000000,
        "file_path": "",
        "status": "not_downloaded",
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "openrail",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"requires_base_model": "runwayml/stable-diffusion-v1-5"},
        "notes": "Helper model; best paired with an SD1.5 base pipeline.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000011"),
        "model_id": "lllyasviel/control_v11p_sd15_lineart",
        "name": "ControlNet Lineart SD1.5",
        "preferred_name": "ControlNet Lineart SD1.5",
        "source": "huggingface",
        "family": "controlnet",
        "variant": "lineart-sd15",
        "description": "Best for: sketch-based and line-based workflows. This is a helper model. Strengths: follows outlines well and keeps drawing structure much better than generic image-to-image. Best helper target: pair it with SD 1.5 Test Model for lightweight testing, or with another SD1.5-compatible illustration base if you add one later. Use it for sketch_to_ink and controlled illustration rendering.",
        "tags": ["controlnet", "adapter", "helper", "image_to_image", "sketch_to_ink", "lineart-guided", "illustration-control", "structure-preserving"],
        "source_url": "https://huggingface.co/lllyasviel/control_v11p_sd15_lineart",
        "version": "1.0",
        "capabilities": ["image_to_image", "sketch_to_ink"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 1450000000,
        "file_path": "",
        "status": "not_downloaded",
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "openrail",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"requires_base_model": "runwayml/stable-diffusion-v1-5"},
        "notes": "Helper model; corrected replacement for the wrong lineart entry.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000012"),
        "model_id": "lllyasviel/control_v11p_sd15_inpaint",
        "name": "ControlNet Inpaint SD1.5",
        "preferred_name": "ControlNet Inpaint SD1.5",
        "source": "huggingface",
        "family": "controlnet",
        "variant": "inpaint-sd15",
        "description": "Best for: masked edits where only part of the image should change. This is a helper model. Strengths: localized control, safer partial recoloring, and better containment of edits. Best helper target: pair it with SD 1.5 Test Model for lightweight masked editing, or with another SD1.5-compatible base if you later add a stronger SD1.5 checkpoint. Use it when the change must stay inside a selected region.",
        "tags": ["controlnet", "adapter", "helper", "image_to_image", "recolor_image", "inpainting", "masked-edit", "localized-edit", "partial-recolor"],
        "source_url": "https://huggingface.co/lllyasviel/control_v11p_sd15_inpaint",
        "version": "1.1",
        "capabilities": ["image_to_image", "recolor_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 1450000000,
        "file_path": "",
        "status": "not_downloaded",
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "openrail",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"requires_base_model": "runwayml/stable-diffusion-v1-5", "input_type": "image+mask"},
        "notes": "Helper model for localized edits and partial recoloring.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000013"),
        "model_id": "lllyasviel/control_v11f1e_sd15_tile",
        "name": "ControlNet Tile SD1.5",
        "preferred_name": "ControlNet Tile SD1.5",
        "source": "huggingface",
        "family": "controlnet",
        "variant": "tile-sd15",
        "description": "Best for: detail enhancement, tiled restoration, and upscale-adjacent workflows. This is a helper model. Strengths: helps recover texture and local detail while keeping the overall image recognizable. Best helper target: pair it with SD 1.5 Test Model for lightweight enhancement tests, or with another SD1.5-compatible base for stronger restoration workflows. Use it when you want enhancement and cleanup more than creative redesign.",
        "tags": ["controlnet", "adapter", "helper", "upscale_image", "image_to_image", "detail-restoration", "texture-enhancement", "tile-control", "enhancement"],
        "source_url": "https://huggingface.co/lllyasviel/control_v11f1e_sd15_tile",
        "version": "1.1",
        "capabilities": ["image_to_image", "upscale_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 1450000000,
        "file_path": "",
        "status": "not_downloaded",
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "openrail",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"requires_base_model": "runwayml/stable-diffusion-v1-5"},
        "notes": "Helper model for enhancement and restoration-style upscale flows.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000014"),
        "model_id": "TencentARC/t2i-adapter-sketch-sdxl-1.0",
        "name": "T2I Adapter Sketch SDXL",
        "preferred_name": "Sketch SDXL Adapter",
        "source": "huggingface",
        "family": "t2i_adapter",
        "variant": "sketch-sdxl",
        "description": "Best for: turning rough sketches into cleaner rendered images while keeping the sketch structure. This is a helper model. Strengths: strong sketch guidance, better pose and shape retention, and cleaner control than generic image-to-image. Best helper target: pair it with SDXL 1.0 for your main SDXL sketch_to_ink workflow. Use it for sketch-to-render or sketch_to_ink flows where structure matters.",
        "tags": ["adapter", "helper", "image_to_image", "sketch_to_ink", "sketch-guided", "shape-preserving", "illustration-control", "render-from-sketch"],
        "source_url": "https://huggingface.co/TencentARC/t2i-adapter-sketch-sdxl-1.0",
        "version": "1.0",
        "capabilities": ["image_to_image", "sketch_to_ink"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 300000000,
        "file_path": "",
        "status": "not_downloaded",
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 8,
        "recommended_vram_max_gb": 16,
        "license": "apache-2.0",
        "base_model": "sdxl",
        "precision": "fp16",
        "requirements": {"requires_base_model": "stabilityai/stable-diffusion-xl-base-1.0", "input_type": "sketch"},
        "notes": "Primary SDXL helper for sketch-guided workflows.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000015"),
        "model_id": "TencentARC/t2i-adapter-canny-sdxl-1.0",
        "name": "T2I Adapter Canny SDXL",
        "preferred_name": "Canny SDXL Adapter",
        "source": "huggingface",
        "family": "t2i_adapter",
        "variant": "canny-sdxl",
        "description": "Best for: controlled generation from edge maps and strong shape guidance. This is a helper model. Strengths: follows object boundaries and layout closely, making edits more predictable. Best helper target: pair it with SDXL 1.0 for controlled image_to_image or recolor_image workflows where composition consistency matters. Use it when layout control matters more than freeform creativity.",
        "tags": ["adapter", "helper", "image_to_image", "recolor_image", "edge-guided", "structure-preserving", "layout-control", "canny"],
        "source_url": "https://huggingface.co/TencentARC/t2i-adapter-canny-sdxl-1.0",
        "version": "1.0",
        "capabilities": ["image_to_image", "recolor_image"],
        "total_size_bytes": 0,
        "disk_size_bytes": 0,
        "download_size_bytes": 300000000,
        "file_path": "",
        "status": "not_downloaded",
        "checksum": "",
        "is_verified": False,
        "recommended_vram_min_gb": 8,
        "recommended_vram_max_gb": 16,
        "license": "apache-2.0",
        "base_model": "sdxl",
        "precision": "fp16",
        "requirements": {"requires_base_model": "stabilityai/stable-diffusion-xl-base-1.0", "input_type": "edge-map"},
        "notes": "Primary SDXL helper for edge-guided controlled edits.",
    },
]


def upgrade() -> None:
    """Insert seed model records using INSERT ... ON CONFLICT DO NOTHING."""
    conn = op.get_bind()
    meta = sa.MetaData()
    models_table = sa.Table(
        "models",
        meta,
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True)),
        sa.Column("model_id", sa.String(512)),
        sa.Column("name", sa.String(255)),
        sa.Column("preferred_name", sa.String(255)),
        sa.Column("source", sa.String(50)),
        sa.Column("family", sa.String(50)),
        sa.Column("variant", sa.String(100)),
        sa.Column("description", sa.Text),
        sa.Column("tags", sa.dialects.postgresql.JSONB),
        sa.Column("source_url", sa.String(1024)),
        sa.Column("version", sa.String(100)),
        sa.Column("capabilities", sa.dialects.postgresql.JSONB),
        sa.Column("total_size_bytes", sa.BigInteger),
        sa.Column("disk_size_bytes", sa.BigInteger),
        sa.Column("download_size_bytes", sa.BigInteger),
        sa.Column("file_path", sa.String(1024)),
        sa.Column("status", sa.String(50)),
        sa.Column("checksum", sa.String(512)),
        sa.Column("is_verified", sa.Boolean),
        sa.Column("recommended_vram_min_gb", sa.Integer),
        sa.Column("recommended_vram_max_gb", sa.Integer),
        sa.Column("license", sa.String(200)),
        sa.Column("base_model", sa.String(100)),
        sa.Column("precision", sa.String(20)),
        sa.Column("requirements", sa.dialects.postgresql.JSONB),
        sa.Column("notes", sa.Text),
        sa.Column("created_at", sa.DateTime),
        sa.Column("updated_at", sa.DateTime),
    )

    # Get current timestamp
    now = datetime.now(timezone.utc)

    # Prepare model records
    model_records = []
    for model_data in MODELS_TO_SEED:
        record = model_data.copy()
        record["created_at"] = now
        record["updated_at"] = now
        model_records.append(record)

    # Insert all models, skipping duplicates
    if model_records:
        for record in model_records:
            # Serialize JSONB fields as JSON strings for raw SQL compatibility
            record["tags"] = json.dumps(record["tags"])
            record["capabilities"] = json.dumps(record["capabilities"])
            record["requirements"] = json.dumps(record["requirements"])
            conn.execute(
                text(
                    "INSERT INTO models (id, model_id, name, preferred_name, source, family, variant, description, tags, source_url, version, capabilities, total_size_bytes, disk_size_bytes, download_size_bytes, file_path, status, checksum, is_verified, recommended_vram_min_gb, recommended_vram_max_gb, license, base_model, precision, requirements, notes, created_at, updated_at) "
                    "VALUES (:id, :model_id, :name, :preferred_name, :source, :family, :variant, :description, CAST(:tags AS jsonb), :source_url, :version, CAST(:capabilities AS jsonb), :total_size_bytes, :disk_size_bytes, :download_size_bytes, :file_path, :status, :checksum, :is_verified, :recommended_vram_min_gb, :recommended_vram_max_gb, :license, :base_model, :precision, CAST(:requirements AS jsonb), :notes, :created_at, :updated_at) "
                    "ON CONFLICT (model_id) DO NOTHING"
                ),
                record,
            )


def downgrade() -> None:
    """Remove all seed model records."""
    conn = op.get_bind()
    meta = sa.MetaData()
    models_table = sa.Table(
        "models",
        meta,
        sa.Column("model_id", sa.String(512)),
    )
    model_ids = [m["model_id"] for m in MODELS_TO_SEED]
    conn.execute(models_table.delete().where(models_table.c.model_id.in_(model_ids)))