"""Seed SD 1.5 family — base models, ControlNet, LoRA, VAE.

Revision ID: 004_seed_sd15
Revises: 003_seed_sdxl
Create Date: 2026-06-15
"""

from __future__ import annotations

import uuid

from seed_helpers import seed_models, unseed_models

revision = "004_seed_sd15"
down_revision = "003_seed_sdxl"
branch_labels = None
depends_on = None

MODELS = [
    # ── SD 1.5 base checkpoints ───────────────────────────────────────────
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000003"),
        "model_id": "runwayml/stable-diffusion-v1-5",
        "name": "SD 1.5 Test Model",
        "preferred_name": "SD 1.5 Test Model",
        "source": "huggingface",
        "family": "stable_diffusion_1",
        "variant": "1.5",
        "model_type": "base_diffusion",
        "compatible_bases": [],
        "description": (
            "Fast, lightweight SD 1.5 base model for development, testing, previews, integration checks, "
            "and low-cost pipeline validation. Use it to test text-to-image, image-to-image, masking, "
            "ControlNet, LoRAs, and end-to-end queue / API behavior before switching to heavier models."
        ),
        "short_description": "Lightweight SD1.5 base for fast dev, testing, previews, and pipeline validation",
        "tags": [
            "sd15",
            "base",
            "fast",
            "test",
            "development",
            "preview",
            "text",
            "img2img",
            "all_rounder",
        ],
        "source_url": "https://huggingface.co/runwayml/stable-diffusion-v1-5",
        "version": "1.5",
        "capabilities": ["text_to_image", "image_to_image"],
        "total_size_bytes": 0,
        "download_size_bytes": 4260000000,
        "status": "not_downloaded",
        "recommended_vram_min_gb": 4,
        "recommended_vram_max_gb": 10,
        "license": "creativeml-openrail-m",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"recommended_resolution": "512x512"},
        "notes": "Primary fast testing model.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000006"),
        "model_id": "lambdalabs/sd-image-variations-diffusers",
        "name": "Stable Image Variations",
        "preferred_name": "Stable Image Variations",
        "source": "huggingface",
        "family": "stable_diffusion_1",
        "variant": "image_variations",
        "model_type": "base_diffusion",
        "compatible_bases": [],
        "description": (
            "Specialized SD 1.5-family model for generating alternate variations of an input image. "
            "Best for identity-preserving image variation, concept variation, and iterative visual exploration."
        ),
        "short_description": "Variation model for generating alternate versions of an existing image",
        "tags": [
            "sd15",
            "base",
            "variation",
            "image_variation",
            "identity",
            "img2img",
            "exploration",
        ],
        "source_url": "https://huggingface.co/lambdalabs/sd-image-variations-diffusers",
        "version": "2.0",
        "capabilities": ["image_to_image"],
        "total_size_bytes": 0,
        "download_size_bytes": 4200000000,
        "status": "not_downloaded",
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "creativeml-openrail-m",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"input_type": "image"},
        "notes": "Use for visual variation workflows.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000007"),
        "model_id": "timbrooks/instruct-pix2pix",
        "name": "InstructPix2Pix",
        "preferred_name": "InstructPix2Pix",
        "source": "huggingface",
        "family": "stable_diffusion_edit",
        "variant": "pix2pix",
        "model_type": "base_diffusion",
        "compatible_bases": [],
        "description": (
            "Instruction-based image editing model for prompt-driven modifications such as recoloring, "
            "style changes, scene mood changes, and object-level editing. Good for direct edit-by-text workflows."
        ),
        "short_description": "Prompt-based image editor for recolor, style transfer, and guided edits",
        "tags": [
            "sd15",
            "base",
            "edit",
            "pix2pix",
            "recolor",
            "style_transfer",
            "instruction",
            "img2img",
        ],
        "source_url": "https://huggingface.co/timbrooks/instruct-pix2pix",
        "version": "1.0",
        "capabilities": ["image_to_image", "recolor_image"],
        "total_size_bytes": 0,
        "download_size_bytes": 4900000000,
        "status": "not_downloaded",
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "openrail",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"input_type": "image"},
        "notes": "Primary edit-by-text SD1.5 model.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000031"),
        "model_id": "sd15-anime-specialist",
        "name": "SD1.5 Anime Specialist",
        "preferred_name": "SD1.5 Anime Specialist",
        "source": "huggingface",
        "family": "custom",
        "variant": "anime-sd15",
        "model_type": "base_diffusion",
        "compatible_bases": [],
        "description": (
            "Anime / manga-oriented SD1.5 placeholder entry for fast stylized testing, character prompting, "
            "and low-cost anime pipeline validation. Intended for users who want a lightweight anime checkpoint."
        ),
        "short_description": "Lightweight SD1.5 anime / manga base for fast stylized testing",
        "tags": [
            "sd15",
            "base",
            "anime",
            "manga",
            "stylized",
            "character",
            "illustration",
            "text",
            "img2img",
            "fast",
        ],
        "source_url": "https://huggingface.co/search?q=sd15+anime",
        "capabilities": ["text_to_image", "image_to_image"],
        "notes": "Catalog placeholder for a lightweight SD1.5 anime checkpoint.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000032"),
        "model_id": "sd15-nsfw-specialist",
        "name": "SD1.5 NSFW Specialist",
        "preferred_name": "SD1.5 NSFW Specialist",
        "source": "huggingface",
        "family": "custom",
        "variant": "nsfw-sd15",
        "model_type": "base_diffusion",
        "compatible_bases": [],
        "description": (
            "Adult-oriented SD1.5 placeholder entry for fast NSFW pipeline testing and low-cost mature-content workflows. "
            "Useful if you want a cheap checkpoint for adult prompt validation before switching to larger models."
        ),
        "short_description": "Lightweight SD1.5 adult / NSFW base for fast testing workflows",
        "tags": [
            "sd15",
            "base",
            "nsfw",
            "adult",
            "erotic",
            "mature",
            "text",
            "img2img",
            "fast",
        ],
        "source_url": "https://huggingface.co/search?q=sd15+nsfw",
        "capabilities": ["text_to_image", "image_to_image"],
        "notes": "Catalog placeholder for a lightweight SD1.5 NSFW checkpoint.",
    },

    # ── ControlNet — SD 1.5 ───────────────────────────────────────────────
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000010"),
        "model_id": "lllyasviel/control_v11f1p_sd15_depth",
        "name": "ControlNet Depth SD1.5",
        "preferred_name": "ControlNet Depth SD1.5",
        "source": "huggingface",
        "family": "controlnet",
        "variant": "depth-sd15",
        "model_type": "controlnet",
        "compatible_bases": ["sd1.5"],
        "description": (
            "Depth-guided ControlNet for SD1.5. Best for structure-aware image editing where perspective, "
            "spatial arrangement, and foreground / background relationships must be preserved."
        ),
        "short_description": "Depth-guided SD1.5 control model for spatially coherent image editing",
        "tags": [
            "sd15",
            "controlnet",
            "depth",
            "spatial",
            "perspective",
            "structure",
            "img2img",
            "helper",
        ],
        "source_url": "https://huggingface.co/lllyasviel/control_v11f1p_sd15_depth",
        "version": "1.1",
        "capabilities": ["image_to_image", "recolor_image"],
        "total_size_bytes": 0,
        "download_size_bytes": 1450000000,
        "status": "not_downloaded",
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "openrail",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"requires_base_model": "runwayml/stable-diffusion-v1-5"},
        "notes": "Good for scene geometry preservation.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000011"),
        "model_id": "lllyasviel/control_v11p_sd15_lineart",
        "name": "ControlNet Lineart SD1.5",
        "preferred_name": "ControlNet Lineart SD1.5",
        "source": "huggingface",
        "family": "controlnet",
        "variant": "lineart-sd15",
        "model_type": "controlnet",
        "compatible_bases": ["sd1.5"],
        "description": (
            "Lineart / sketch ControlNet for SD1.5. Best for sketch-to-image, sketch-to-ink, comic workflows, "
            "and preserving drawing structure from line-based inputs."
        ),
        "short_description": "Lineart / sketch SD1.5 control model for sketch-to-image and inking workflows",
        "tags": [
            "sd15",
            "controlnet",
            "lineart",
            "sketch",
            "sketch_to_image",
            "sketch_to_ink",
            "comic",
            "img2img",
            "helper",
        ],
        "source_url": "https://huggingface.co/lllyasviel/control_v11p_sd15_lineart",
        "version": "1.0",
        "capabilities": ["image_to_image", "sketch_to_ink"],
        "total_size_bytes": 0,
        "download_size_bytes": 1450000000,
        "status": "not_downloaded",
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "openrail",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"requires_base_model": "runwayml/stable-diffusion-v1-5"},
        "notes": "Primary SD1.5 sketch and lineart helper.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000012"),
        "model_id": "lllyasviel/control_v11p_sd15_inpaint",
        "name": "ControlNet Inpaint SD1.5",
        "preferred_name": "ControlNet Inpaint SD1.5",
        "source": "huggingface",
        "family": "controlnet",
        "variant": "inpaint-sd15",
        "model_type": "controlnet",
        "compatible_bases": ["sd1.5"],
        "description": (
            "Masked-edit ControlNet for SD1.5. Use it for localized modifications, inpainting, partial recoloring, "
            "object replacement, face-region edits, and controlled edits where only part of the image should change."
        ),
        "short_description": "Masked-edit SD1.5 control model for inpainting and localized image edits",
        "tags": [
            "sd15",
            "controlnet",
            "inpaint",
            "mask",
            "masked_edit",
            "localized_edit",
            "recolor",
            "img2img",
            "helper",
        ],
        "source_url": "https://huggingface.co/lllyasviel/control_v11p_sd15_inpaint",
        "version": "1.1",
        "capabilities": ["image_to_image", "recolor_image"],
        "total_size_bytes": 0,
        "download_size_bytes": 1450000000,
        "status": "not_downloaded",
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "openrail",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {
            "requires_base_model": "runwayml/stable-diffusion-v1-5",
            "input_type": "image+mask",
        },
        "notes": "Primary SD1.5 inpainting / local editing helper.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000013"),
        "model_id": "lllyasviel/control_v11f1e_sd15_tile",
        "name": "ControlNet Tile SD1.5",
        "preferred_name": "ControlNet Tile SD1.5",
        "source": "huggingface",
        "family": "controlnet",
        "variant": "tile-sd15",
        "model_type": "controlnet",
        "compatible_bases": ["sd1.5"],
        "description": (
            "Tile / detail-restoration ControlNet for SD1.5. Best for enhancement, recovery of local detail, "
            "upscale follow-up passes, and diffusion-based restoration of noisy or degraded images."
        ),
        "short_description": "Tile/detail SD1.5 control model for restoration, enhancement, and upscale follow-up",
        "tags": [
            "sd15",
            "controlnet",
            "tile",
            "detail",
            "restoration",
            "enhancement",
            "upscale",
            "noise",
            "img2img",
            "helper",
        ],
        "source_url": "https://huggingface.co/lllyasviel/control_v11f1e_sd15_tile",
        "version": "1.1",
        "capabilities": ["image_to_image", "upscale_image"],
        "total_size_bytes": 0,
        "download_size_bytes": 1450000000,
        "status": "not_downloaded",
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "openrail",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"requires_base_model": "runwayml/stable-diffusion-v1-5"},
        "notes": "Strong helper for restoration and detail-recovery workflows.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000021"),
        "model_id": "lllyasviel/control_v11p_sd15_openpose",
        "name": "ControlNet OpenPose SD1.5",
        "preferred_name": "OpenPose ControlNet SD1.5",
        "source": "huggingface",
        "family": "controlnet",
        "variant": "openpose-sd15",
        "model_type": "controlnet",
        "compatible_bases": ["sd1.5"],
        "description": (
            "OpenPose / skeleton-guided ControlNet for SD1.5. Use it for human pose transfer, character posing, "
            "animation pose matching, and keeping body posture consistent across outputs."
        ),
        "short_description": "Pose-guided SD1.5 control model for human pose transfer and character posing",
        "tags": [
            "sd15",
            "controlnet",
            "openpose",
            "pose",
            "character",
            "human",
            "body",
            "img2img",
            "helper",
        ],
        "source_url": "https://huggingface.co/lllyasviel/control_v11p_sd15_openpose",
        "version": "1.1",
        "capabilities": ["image_to_image"],
        "total_size_bytes": 0,
        "download_size_bytes": 1450000000,
        "status": "not_downloaded",
        "recommended_vram_min_gb": 6,
        "recommended_vram_max_gb": 12,
        "license": "openrail",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"requires_base_model": "runwayml/stable-diffusion-v1-5"},
        "notes": "Primary SD1.5 pose-guidance helper.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000033"),
        "model_id": "lllyasviel/control_v11p_sd15_canny",
        "name": "ControlNet Canny SD1.5",
        "preferred_name": "ControlNet Canny SD1.5",
        "source": "huggingface",
        "family": "controlnet",
        "variant": "canny-sd15",
        "model_type": "controlnet",
        "compatible_bases": ["sd1.5"],
        "description": (
            "Canny / edge-guided ControlNet for SD1.5. Best for structure-preserving editing, redraw passes, "
            "layout lock, silhouette retention, and controlled image transformations from edge maps."
        ),
        "short_description": "Canny / edge SD1.5 control model for structure-preserving image editing",
        "tags": [
            "sd15",
            "controlnet",
            "canny",
            "edge",
            "structure",
            "composition",
            "img2img",
            "helper",
        ],
        "source_url": "https://huggingface.co/search?q=controlnet+canny+sd15",
        "capabilities": ["image_to_image"],
        "notes": "Useful for edge-driven SD1.5 edits.",
    },

    # ── LoRA — SD 1.5 ────────────────────────────────────────────────────
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000024"),
        "model_id": "latent-consistency/lcm-lora-sdv1-5",
        "name": "LCM LoRA SD1.5",
        "preferred_name": "LCM LoRA SD1.5",
        "source": "huggingface",
        "family": "lora",
        "variant": "lcm-sd15",
        "model_type": "lora",
        "compatible_bases": ["sd1.5"],
        "description": (
            "Speed LoRA for SD1.5. Use it for very fast low-step previews, UI testing, prompt iteration, "
            "and development workflows where turnaround time matters more than final quality."
        ),
        "short_description": "Speed LoRA for SD1.5 fast previews and ultra-fast development iteration",
        "tags": [
            "sd15",
            "lora",
            "speed",
            "lcm",
            "fast",
            "preview",
            "development",
            "helper",
        ],
        "source_url": "https://huggingface.co/latent-consistency/lcm-lora-sdv1-5",
        "version": "1.0",
        "capabilities": ["text_to_image", "image_to_image"],
        "total_size_bytes": 0,
        "download_size_bytes": 200000000,
        "status": "not_downloaded",
        "recommended_vram_min_gb": 4,
        "recommended_vram_max_gb": 10,
        "license": "mit",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {
            "requires_base_model": "runwayml/stable-diffusion-v1-5",
            "scheduler": "LCMScheduler",
            "recommended_steps": "4-8",
            "recommended_guidance_scale": "1.0-2.0",
            "lora_strength_default": 1.0,
        },
        "notes": "Primary speed LoRA for SD1.5.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000034"),
        "model_id": "sd15-anime-lora",
        "name": "SD1.5 Anime LoRA",
        "preferred_name": "SD1.5 Anime LoRA",
        "source": "huggingface",
        "family": "lora",
        "variant": "anime-sd15",
        "model_type": "lora",
        "compatible_bases": ["sd1.5"],
        "description": (
            "Anime / manga style LoRA for SD1.5. Intended for lightweight anime testing, stylized character prompts, "
            "cel-shaded looks, expressive faces, and manga-flavored output."
        ),
        "short_description": "Anime / manga LoRA for SD1.5 fast stylized character generation",
        "tags": [
            "sd15",
            "lora",
            "anime",
            "manga",
            "stylized",
            "character",
            "illustration",
            "style",
        ],
        "source_url": "https://huggingface.co/search?q=sd15+anime+lora",
        "capabilities": ["text_to_image", "image_to_image"],
        "notes": "Useful for lightweight stylized SD1.5 testing.",
    },
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000035"),
        "model_id": "sd15-nsfw-lora",
        "name": "SD1.5 NSFW LoRA",
        "preferred_name": "SD1.5 NSFW LoRA",
        "source": "huggingface",
        "family": "lora",
        "variant": "nsfw-sd15",
        "model_type": "lora",
        "compatible_bases": ["sd1.5"],
        "description": (
            "NSFW-oriented LoRA for SD1.5 fast adult-content workflows. Intended for mature prompt testing, "
            "adult character rendering, lingerie / nude variations, and cheap pipeline validation."
        ),
        "short_description": "NSFW LoRA for SD1.5 adult prompt testing and fast mature-content workflows",
        "tags": [
            "sd15",
            "lora",
            "nsfw",
            "adult",
            "erotic",
            "mature",
            "character",
            "style",
        ],
        "source_url": "https://huggingface.co/search?q=sd15+nsfw+lora",
        "capabilities": ["text_to_image", "image_to_image"],
        "notes": "Catalog placeholder for SD1.5 adult-style workflows.",
    },

    # ── VAE — SD 1.5 ─────────────────────────────────────────────────────
    {
        "id": uuid.UUID("a0000000-0000-0000-0000-000000000026"),
        "model_id": "stabilityai/sd-vae-ft-mse",
        "name": "SD VAE ft-MSE",
        "preferred_name": "SD 1.5 VAE MSE",
        "source": "huggingface",
        "family": "vae",
        "variant": "ft-mse",
        "model_type": "vae",
        "compatible_bases": ["sd1.5"],
        "description": (
            "Improved VAE for SD1.5 that reduces color bleeding, improves edge cleanliness, and produces more stable "
            "decoded images than the default SD1.5 VAE. Recommended default VAE companion for SD1.5 pipelines."
        ),
        "short_description": "Improved SD1.5 VAE for cleaner color, fewer artifacts, and better decoding",
        "tags": [
            "sd15",
            "vae",
            "quality",
            "color_fix",
            "artifact_reduction",
            "helper",
        ],
        "source_url": "https://huggingface.co/stabilityai/sd-vae-ft-mse",
        "version": "ft-mse",
        "capabilities": [],
        "total_size_bytes": 0,
        "download_size_bytes": 335000000,
        "status": "not_downloaded",
        "recommended_vram_min_gb": 2,
        "recommended_vram_max_gb": 4,
        "license": "creativeml-openrail-m",
        "base_model": "sd1.5",
        "precision": "fp16",
        "requirements": {"requires_base_family": "sd1.5"},
        "notes": "Recommended default VAE for SD1.5.",
    },
]


def upgrade() -> None:
    seed_models(MODELS)


def downgrade() -> None:
    unseed_models(MODELS)