"""
Default model catalog definitions.

This module defines the initial set of models that should be present in the
database when the application starts. These are NOT pre-downloaded — they are
registered as metadata entries with a `download` flag that tells the seed
migration whether to trigger an initial download job.

Each definition maps directly to a `ModelRecord` row in the `models` table.
"""

from typing import Any

DEFAULT_MODELS: list[dict[str, Any]] = [
    # ─── 🎨 IMAGE GENERATION ───────────────────────────────────────────────
    {
        "model_id": "black-forest-labs/FLUX.1-dev",
        "name": "FLUX.1-dev",
        "source": "huggingface",
        "family": "image",
        "variant": "FLUX.1-dev",
        "description": "High-end image generator with excellent realism and composition. Best open model for near-commercial image quality. Needs 20–24GB VRAM but runs fine on 4090 with optimizations.",
        "tags": ["photorealism", "prompt-adherence", "high-quality", "general"],
        "source_url": "https://huggingface.co/black-forest-labs/FLUX.1-dev",
        "capabilities": ["text-to-image"],
        "download": True,
    },
    {
        "model_id": "black-forest-labs/FLUX.1-schnell",
        "name": "FLUX.1-schnell",
        "source": "huggingface",
        "family": "image",
        "variant": "FLUX.1-schnell",
        "description": "Same family as FLUX-dev but optimized for speed. Great for iterative UI or prompt testing. Slight quality loss but extremely fast.",
        "tags": ["ultra-fast", "preview", "low-steps", "realtime"],
        "source_url": "https://huggingface.co/black-forest-labs/FLUX.1-schnell",
        "capabilities": ["text-to-image"],
        "download": False,
    },
    {
        "model_id": "stabilityai/stable-diffusion-xl-base-1.0",
        "name": "SDXL 1.0 Base",
        "source": "huggingface",
        "family": "image",
        "variant": "SDXL 1.0",
        "description": "Most widely supported modern image model. Huge LoRA ecosystem (Civitai). Best 'default stable pipeline' model.",
        "tags": ["general", "versatile", "ecosystem", "balanced"],
        "source_url": "https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0",
        "capabilities": ["text-to-image"],
        "download": False,
    },
    {
        "model_id": "stabilityai/sdxl-turbo",
        "name": "SDXL Turbo",
        "source": "huggingface",
        "family": "image",
        "variant": "SDXL Turbo",
        "description": "Extreme speed SDXL variant (1–4 steps). Great for testing pipelines or interactive apps.",
        "tags": ["realtime", "ultra-fast", "preview", "low-steps"],
        "source_url": "https://huggingface.co/stabilityai/sdxl-turbo",
        "capabilities": ["text-to-image"],
        "download": False,
    },
    {
        "model_id": "civitai:133005/juggernaut-xl",
        "name": "Juggernaut XL",
        "source": "civitai",
        "family": "image",
        "variant": "Juggernaut XL",
        "description": "One of the best SDXL finetunes for realistic humans and cinematic lighting. Very popular production checkpoint.",
        "tags": ["photorealism", "cinematic", "SDXL finetune", "portrait"],
        "source_url": "https://civitai.com/models/133005/juggernaut-xl",
        "capabilities": ["text-to-image"],
        "download": False,
    },
    {
        "model_id": "civitai:112902/dreamshaper-xl",
        "name": "DreamShaper XL",
        "source": "civitai",
        "family": "image",
        "variant": "DreamShaper XL",
        "description": "Balanced SDXL model for artistic + semi-real outputs. Great general-purpose creative model.",
        "tags": ["stylized", "semi-real", "illustration", "general"],
        "source_url": "https://civitai.com/models/112902/dreamshaper-xl",
        "capabilities": ["text-to-image"],
        "download": False,
    },
    # ─── ✏️ IMAGE EDITING / INPAINTING ───────────────────────────────────
    {
        "model_id": "black-forest-labs/flux-kontext-dev",
        "name": "FLUX Kontext",
        "source": "huggingface",
        "family": "image_edit",
        "variant": "FLUX Kontext dev",
        "description": "Strong prompt-based image editing while preserving identity and composition. Best modern editing model.",
        "tags": ["instruction-editing", "consistency", "object-edit", "photoreal"],
        "source_url": "https://huggingface.co/black-forest-labs/flux-kontext-dev",
        "capabilities": ["image-editing"],
        "download": False,
    },
    {
        "model_id": "runwayml/stable-diffusion-inpainting",
        "name": "SDXL Inpainting",
        "source": "huggingface",
        "family": "image_edit",
        "variant": "Inpainting",
        "description": "Classic inpainting model. Less intelligent than FLUX but extremely compatible with tools and ControlNet workflows.",
        "tags": ["inpainting", "mask-edit", "legacy", "flexible"],
        "source_url": "https://huggingface.co/runwayml/stable-diffusion-inpainting",
        "capabilities": ["inpainting"],
        "download": False,
    },
    # ─── 🧾 IMAGE UNDERSTANDING (VISION) ──────────────────────────────────
    {
        "model_id": "Qwen/Qwen2.5-VL-7B-Instruct",
        "name": "Qwen2.5-VL",
        "source": "huggingface",
        "family": "vision",
        "variant": "Qwen2.5-VL-7B",
        "description": "Excellent vision-language model. Reads charts, UI, screenshots, text-heavy images reliably.",
        "tags": ["OCR", "reasoning", "multimodal", "documents"],
        "source_url": "https://huggingface.co/Qwen/Qwen2.5-VL-7B-Instruct",
        "capabilities": ["image-understanding", "ocr"],
        "download": False,
    },
    {
        "model_id": "OpenGVLab/InternVL2-8B",
        "name": "InternVL2",
        "source": "huggingface",
        "family": "vision",
        "variant": "InternVL2-8B",
        "description": "Strong alternative to Qwen VL, especially good at spatial reasoning and complex image understanding.",
        "tags": ["vision QA", "grounding", "multimodal", "reasoning"],
        "source_url": "https://huggingface.co/OpenGVLab/InternVL2-8B",
        "capabilities": ["image-understanding"],
        "download": False,
    },
    # ─── 🎬 VIDEO GENERATION ──────────────────────────────────────────────
    {
        "model_id": "wan-ai/Wan2.1-T2V-1.3B",
        "name": "Wan 2.1 (small)",
        "source": "huggingface",
        "family": "video",
        "variant": "Wan2.1-T2V-1.3B",
        "description": "Best open video model family. Large variants are heavy, but 1–3B versions run locally with optimizations.",
        "tags": ["text-to-video", "motion", "realistic", "balanced"],
        "source_url": "https://huggingface.co/wan-ai/Wan2.1-T2V-1.3B",
        "capabilities": ["text-to-video"],
        "download": False,
    },
    {
        "model_id": "THUDM/CogVideoX-2b",
        "name": "CogVideoX-2B",
        "source": "huggingface",
        "family": "video",
        "variant": "CogVideoX-2B",
        "description": "Solid lightweight video generation model. Easier to run than Wan large models, good for dev/testing.",
        "tags": ["video", "text-to-video", "stable", "general"],
        "source_url": "https://huggingface.co/THUDM/CogVideoX-2b",
        "capabilities": ["text-to-video"],
        "download": False,
    },
    {
        "model_id": "Lightricks/LTX-Video",
        "name": "LTX-Video",
        "source": "huggingface",
        "family": "video",
        "variant": "LTX-Video",
        "description": "Extremely fast video generation for testing pipelines. Not cinematic but ideal for iteration speed.",
        "tags": ["ultra-fast", "preview", "real-time-ish", "low-quality"],
        "source_url": "https://huggingface.co/Lightricks/LTX-Video",
        "capabilities": ["text-to-video"],
        "download": False,
    },
    # ─── ✏️ BONUS: INK / SKETCH MODELS ────────────────────────────────────
    {
        "model_id": "diffusers/controlnet-sdxl-lineart",
        "name": "SDXL ControlNet Lineart",
        "source": "huggingface",
        "family": "sketch",
        "variant": "ControlNet SDXL Lineart",
        "description": "Converts sketches/ink drawings into structured images. Best general sketch pipeline.",
        "tags": ["sketch-to-image", "lineart", "controlnet", "illustration"],
        "source_url": "https://huggingface.co/diffusers/controlnet-sdxl-lineart",
        "capabilities": ["sketch-to-image"],
        "download": False,
    },
    {
        "model_id": "lllyasviel/control_v11p_sd15_scribble",
        "name": "SD 1.5 ControlNet Scribble",
        "source": "huggingface",
        "family": "sketch",
        "variant": "ControlNet SD1.5 Scribble",
        "description": "Very fast sketch-to-image model. Lower quality than SDXL but excellent responsiveness and huge LoRA ecosystem.",
        "tags": ["scribble", "fast", "control", "anime-friendly"],
        "source_url": "https://huggingface.co/lllyasviel/control_v11p_sd15_scribble",
        "capabilities": ["sketch-to-image"],
        "download": False,
    },
]
</thinking>